services:
  webmonitor:
    image: javieralvarezcu/webmonitorbot:latest
    build:
      context: ./WebMonitorBot
      dockerfile: Dockerfile
      args:
        DOTNET_SDK_VERSION: ${DOTNET_SDK_VERSION:-10.0}
        DOTNET_RUNTIME_VERSION: ${DOTNET_RUNTIME_VERSION:-10.0}
      # platform: ${PLATFORM:-}
    container_name: webmonitor
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      DEEPSEEK__ApiUrl: ${DEEPSEEK__ApiUrl:-https://api.deepseek.com/v1/chat}
      DATABASE_CONN: ${DATABASE_CONN}
      Monitoring__DefaultIntervalSeconds: ${Monitoring__DefaultIntervalSeconds:-300}
    networks:
      - webnet
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  webnet:
    driver: bridge
