// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMonitorBot.Data.EF;

#nullable disable

namespace WebMonitorBot.Data.EF.Migrations
{
    [DbContext(typeof(WebMonitorContext))]
    [Migration("20260526175713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMonitorBot.Data.EF.Models.MonitoringUrlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CheckIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCleanText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonitoringUrls");
                });

            modelBuilder.Entity("WebMonitorBot.Data.EF.Models.WhitelistEntry", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatId"));

                    b.HasKey("ChatId");

                    b.ToTable("Whitelist");
                });
#pragma warning restore 612, 618
        }
    }
}
